[ JSON => DataFrame 저장 다루기 ]

(1) 모듈 로딩 <hr>

In [45]:
import pandas as pd

(2) 데이터 준비

In [46]:
file3='../data/nobel.json'

(3) JSON ==> DataFrame으로 저장

In [47]:
nobelDF=pd.read_json(file3)
nobelDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646 entries, 0 to 645
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   prizes  646 non-null    object
dtypes: object(1)
memory usage: 5.2+ KB

In [48]:
nobelDF.head(3), nobelDF.tail(3)

(                                              prizes
 0  {'year': '2019', 'category': 'chemistry', 'lau...
 1  {'year': '2019', 'category': 'economics', 'lau...
 2  {'year': '2019', 'category': 'literature', 'la...,
                                                 prizes
 643  {'year': '1901', 'category': 'peace', 'laureat...
 644  {'year': '1901', 'category': 'physics', 'laure...
 645  {'year': '1901', 'category': 'medicine', 'laur...)

(4) 데이터 추출

In [49]:
# 행 추출 => iloc[], loc[]
type(nobelDF.iloc[0])

pandas.core.series.Series

In [50]:
oneData = nobelDF.iloc[0]["prizes"]

In [51]:
type(nobelDF.iloc[0]["prizes"]) # 타입이 딕셔너리임을 확인할 수 있다

dict

In [52]:
# 행 추출 => iloc[[n1,...nN]]
nobelDF.iloc[[0,3]] # 여러 행을 뽑아오면 DataFrame이다

                                              prizes
0  {'year': '2019', 'category': 'chemistry', 'lau...
3  {'year': '2019', 'category': 'peace', 'laureat...

In [53]:
oneData.keys()

dict_keys(['year', 'category', 'laureates'])

In [54]:
oneData.items()

dict_items([('year', '2019'), ('category', 'chemistry'), ('laureates', [{'id': '976', 'firstname': 'John', 'surname': 'Goodenough', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '977', 'firstname': 'M. Stanley', 'surname': 'Whittingham', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '978', 'firstname': 'Akira', 'surname': 'Yoshino', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}])])

In [55]:
oneData["laureates"]

[{'id': '976',
  'firstname': 'John',
  'surname': 'Goodenough',
  'motivation': '"for the development of lithium-ion batteries"',
  'share': '3'},
 {'id': '977',
  'firstname': 'M. Stanley',
  'surname': 'Whittingham',
  'motivation': '"for the development of lithium-ion batteries"',
  'share': '3'},
 {'id': '978',
  'firstname': 'Akira',
  'surname': 'Yoshino',
  'motivation': '"for the development of lithium-ion batteries"',
  'share': '3'}]

In [56]:
for k,v in oneData.items():
    print(f'[{k}]\n ==> {v}')
    if k=='laureates':
        for d in v: # v는 딕셔너리가 담긴 리스트라서 한번 풀어헤치고, 
            for k1, v1 in d.items(): # for문을 사용해서 key와 value를 뽑아낸다
                print(k1, v1)
            print()

[year]
 ==> 2019
[category]
 ==> chemistry
[laureates]
 ==> [{'id': '976', 'firstname': 'John', 'surname': 'Goodenough', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '977', 'firstname': 'M. Stanley', 'surname': 'Whittingham', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}, {'id': '978', 'firstname': 'Akira', 'surname': 'Yoshino', 'motivation': '"for the development of lithium-ion batteries"', 'share': '3'}]
id 976
firstname John
surname Goodenough
motivation "for the development of lithium-ion batteries"
share 3

id 977
firstname M. Stanley
surname Whittingham
motivation "for the development of lithium-ion batteries"
share 3

id 978
firstname Akira
surname Yoshino
motivation "for the development of lithium-ion batteries"
share 3

- json 중첩 데이터의 다중 반복문 => 단일 리스트 형태 처리 : 평탄화/정규화

In [58]:
pd.json_normalize(oneData, record_path="laureates")

,id,firstname,surname,motivation,share
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3

In [59]:
pd.json_normalize(oneData, record_path="laureates", meta=["year","category"])

,id,firstname,surname,motivation,share,year,category
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3,2019,chemistry
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3,2019,chemistry
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3,2019,chemistry

In [69]:
# 아래 코드를 실행하기 전에, 모든 딕셔너리에 대해 record_path에 해당하는 키 생성하기
for data in nobelDF.prizes:
    print(type(data), data.keys(), end="\n\n")
    # 해당 dict에 laureates 키가 없다면 추가 
    data.setdefault('laureates',[])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'overallMotivation', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])

<class 'dict'> dict_keys(['year', 'category', 'laureates'])


In [70]:
# 컬럼 읽기 => DF객체변수명[컬럼명],DF객체변수명.컬럼명
pd.json_normalize(nobelDF.prizes, record_path='laureates') 
# -> laureates에 대한 에러가 뜬다면 없는 애가 없다는 것이다
# -> 모든행에 record_path에 해당하는 키(key)가 존재해야 함!

,id,firstname,surname,motivation,share
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3
3,982,Abhijit,Banerjee,"""for their experimental approach to alleviatin...",3
4,983,Esther,Duflo,"""for their experimental approach to alleviatin...",3
...,...,...,...,...,...
945,569,Sully,Prudhomme,"""in special recognition of his poetic composit...",1
946,462,Henry,Dunant,"""for his humanitarian efforts to help wounded ...",2
947,463,Frédéric,Passy,"""for his lifelong work for international peace...",2
948,1,Wilhelm Conrad,Röntgen,"""in recognition of the extraordinary services ...",1
949,293,Emil,von Behring,"""for his work on serum therapy, especially its...",1

In [72]:
nobleDF2=pd.json_normalize(nobelDF.prizes, record_path='laureates',meta=['year','category'])
nobleDF2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          950 non-null    object
 1   firstname   950 non-null    object
 2   surname     921 non-null    object
 3   motivation  950 non-null    object
 4   share       950 non-null    object
 5   year        950 non-null    object
 6   category    950 non-null    object
dtypes: object(7)
memory usage: 52.1+ KB

- (7) JSON의 다양한 방식의 DataFrame 저장 => orient 파라미터

In [73]:
# 딕셔너리 => 키 : 밸류
# 첫번째 케이스 : 키가 없는 상태
json_data=''' 
[
{"id" : "1","name":"sravan","age":22},
{"id" : "2","name":"harsha","age":22},
{"id" : "3","name":"deepika","age":21},
{"id" : "4","name":"jyothika","age":23}
]
'''

- orient = 'record' 설정 => JSON 파일 데이터를 행 단위로 읽어서 DataFrame에 저장

In [98]:
df=pd.read_json(json_data, orient = 'record') #json객체가 여러 개 있는 배열로 판단하고, 한 행씩 읽어들인다
# 한 json객체를 레코드(행)로 본다
# 한 중괄호 덩어리를 json객체라 본다
print(df)

   id      name  age
0   1    sravan   22
1   2    harsha   22
2   3   deepika   21
3   4  jyothika   23

In [96]:
# 키가 하나 붙어있는 상태
# 키 : 밸류, 키: 밸류....형식이다
# 키는 컬럼명으로 두고, 밸류는 레코드(행)로 본다
# 아까의 json_data에서는 키값이 없어서 read_json했을 때 인덱스값이 안들어갔었다
# 딕셔너리 안에 딕셔너리가 있는 형태일 때, orient='index'나 'columns'를 쓸 수 있다!
json_data2=''' 
{
    "Student1" : {"id" : "1","name":"sravan","age":22},
    "Student2" : {"id" : "2","name":"harsha","age":22},
    "Student3" : {"id" : "3","name":"deepika","age":21},
    "Student4" : {"id" : "4","name":"jyothika","age":23}
}
'''

In [97]:
df=pd.read_json(json_data2, orient='index') #, orient="
print(df)

          id      name  age
Student1   1    sravan   22
Student2   2    harsha   22
Student3   3   deepika   21
Student4   4  jyothika   23

In [87]:
df=pd.read_json(json_data2, orient='columns') #, orient="records")
print(df)

     Student1 Student2 Student3  Student4
id          1        2        3         4
name   sravan   harsha  deepika  jyothika
age        22       22       21        23

In [88]:
df=pd.read_json(json_data2, orient='columns').T
print(df)

         id      name age
Student1  1    sravan  22
Student2  2    harsha  22
Student3  3   deepika  21
Student4  4  jyothika  23

In [92]:
# JSON Format # 키와 밸류 쌍이 없고, 오직 값밖에 없다
json_data3 = '''
[
    [ "1", "sravan",22 ],
    [ "2", "harsha",22 ],
    [ "3", "deepika",21 ],
    [ "4", "jyothika",23 ]
]
'''

In [93]:
df=pd.read_json(json_data3, orient='values') # 단지 값만 들어있다고 표시
df

   0         1   2
0  1    sravan  22
1  2    harsha  22
2  3   deepika  21
3  4  jyothika  23